# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180702_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='userconta',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConta',
        ),
    ]
